Revert "Speed up digesting by avoiding unnecessary operations."
This reverts commit 5041dd13c9499e4154436ef1f105a3d5d46caa19.

This change broke a libcore test:
 org.apache.harmony.security.tests.java.security.DigestInputStream2Test#test_onZ
    java.lang.RuntimeException: Unable to copy EVP_MD_CTX
    	at com.android.org.conscrypt.NativeCrypto.EVP_MD_CTX_copy(Native Method)
    	at com.android.org.conscrypt.OpenSSLMessageDigestJDK.clone(OpenSSLMessageDigestJDK.java:200)
    	at java.security.MessageDigest$MessageDigestImpl.clone(MessageDigest.java:428)
    	at org.apache.harmony.security.tests.java.security.DigestInputStream2Test.test_onZ(DigestInputStream2Test.java:62)
  org.apache.harmony.security.tests.java.security.DigestInputStream2Test#test_onZ FAIL (EXEC_FAILED)

Change-Id: Ib925bc0aadb633bbad4240f1d52bdb6676afc56f