Don't init cipher suites if native code didn't load.
The try/catch and setting of loadError prevents the first static
initializer in NativeCrypto from rendering the class unloadable, but
the second static initializer still does, which means that users tend
to get NoClassDefFoundErrors when they try to use Conscrypt instead of
a more useful UnsatisfiedLinkError that points to the root cause.