Specify the class explicitly in SSLSocket test
Otherwise this causes compile errors on the Android compiler:
error: incompatible types: List<SocketType> cannot be converted to
Iterable<Object>